modLoader="javafml"
loaderVersion="[51,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="equipmentcompare"
version="${version}"
displayName="Equipment Compare"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/502561"
logoFile="icon.png"
authors="Grend"
description='''Adds additional tooltips when hovering over equipment for easy comparisons.'''

[[dependencies.equipmentcompare]]
	modId="forge"
	mandatory=true
	versionRange="[51,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.2.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="legendarytooltips"
	mandatory=false
	versionRange="[1.4.7,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="curios"
	mandatory=false
	versionRange="[9.0.3,)"
	ordering="NONE"
	side="BOTH"