modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="equipmentcompare"
version="${version}"
displayName="Equipment Compare"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/502561"
logoFile="icon.png"
authors="Grend"
description='''Adds additional tooltips when hovering over equipment for easy comparisons.'''

[[dependencies.equipmentcompare]]
	modId="neoforge"
	type="required"
	versionRange="[21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="minecraft"
	type="required"
	versionRange="[1.21,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="iceberg"
	type="required"
	versionRange="[1.2.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="legendarytooltips"
	type="optional"
	versionRange="[1.4.7,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="curios"
	type="optional"
	versionRange="[9.0.3,)"
	ordering="NONE"
	side="BOTH"

[[mixins]]
	config="equipmentcompare.mixins.json"